* *Dotfiles*
  A small collection of my personal configuration files I frequently use.
  
  These configurations shall work on any *recent* GNU/Linux.
  - *Note:* This is a work in progress. This is _not yet ready_ to
    be used on production systems.

* Why do I need this?
  
  One of my role at work is system administration. I will have
  to install Operating Systems (GNU/Linux based) on many client's
  machines.

  So I use this to automate the configuration of those systems,
  which may later be used to automate the installations too.

  Currently these are my focuses:
  - Debian GNU/Linux
  - GNOME Desktop Environment

  Hopefully this shall be helpful for you too.

* Configuration files present
  - git
    - gitignore
    - gitconfig
    - ssh config
  - GNU Emacs (basic configuration only)

* License
  - Written by Mohammed Sadik <sadiq@sadiqpk.org>
  - Year: 2015 -- 2016
  
  To the extent possible under law, the author have dedicated all copyright
  and related and neighboring rights to this software to the public domain
  worldwide. This software is distributed _without any warranty_.
  
  You should have received a copy of the CC0 Public Domain Dedication along
  with this software. If not, see
  [[http://creativecommons.org/publicdomain/zero/1.0/]].
