* *Dotfiles*
  A small collection of my personal configuration files I plan to use frequently.
  
  These configurations shall work on any *recent* GNU/Linux.
  - *Note:* This is a work in progress. This is _not yet ready_ to
    be used on production systems.

* Why do I need this?
  
  One of my role at work is system administration. I will have
  to install Operating Systems (GNU/Linux based) on many client's
  machines.

  So I'm planning to use this script to automate the configuration of those
  systems, which may later be used to automate the installations too.

  Currently these are my focuses:
  - Debian GNU/Linux
  - GNOME Desktop Environment (3.18+)

  Hopefully this shall be helpful for you too.

* How to Configure my system with these dotfiles?

  - Edit the file =settings.sh=
    - Set the variables with the configuration you wish
  - Also, If you don't wish to mess your current settings please look
    into the files =gsettings.sh= and =gtk-ui.sh= in the =scripts=
    directory before you run =make=.
  - Now execute =make=
    - You may also try =silent= or =verbose= with =make= (Eg.: =make verbose=)
    - Alternatively, you may run =./configure= to be more verbose
      or if GNU make is not available for you
  - Your system is configured.

** Notes
   - After your system is configured, you can edit the file =~/.bash/personal=
     to add your personal =.bashrc= scripts. This file won't ever be over
     written even if =OVERWRITE= is set to `true' in =settings.sh=
    
* Configuration files present
  - GNOME Desktop Environment
    - Font
    - Theme
  - git
  - Bash
  - GNU Emacs (basic configuration only)
  - Editorconfig (ONE config for every editor)

    Note: This script may be capable to configure Cinnamon and Mate DEs.

* License

  Copyright (c) 2015, 2016 Mohammed Sadik <sadiq@sadiqpk.org>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but *without any warranty*; without even the implied warranty of
  *merchantability* or *fitness for a particular purpose*.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see [[http://www.gnu.org/licenses/]].
