* *Dotfiles*
  A small collection of my personal configuration files I frequently use.
  
  These configurations shall work on any *recent* GNU/Linux.
  - *Note:* This is a work in progress. This is _not yet ready_ to
    be used on production systems.

* Why do I need this?
  
  One of my role at work is system administration. I will have
  to install Operating Systems (GNU/Linux based) on many client's
  machines.

  So I use this to automate the configuration of those systems,
  which may later be used to automate the installations too.

  Currently these are my focuses:
  - Debian GNU/Linux
  - GNOME Desktop Environment

  Hopefully this shall be helpful for you too.

* How to use these dotfiles?

  - Edit the file =settings.sh=
    - Set the variables with the configuration you wish
  - Now execute =./configure=
  - Your system is configured.

* Configuration files present
  - GNOME Desktop Environment
  - git
  - GNU Emacs (basic configuration only)

* License

  Copyright (c) 2015, 2016 Mohammed Sadik <sadiq@sadiqpk.org>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but *without any warranty*; without even the implied warranty of
  *merchantability* or *fitness for a particular purpose*.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see [[http://www.gnu.org/licenses/]].
