# -*- mode: shell-script; -*-

if [ "$UID" -eq 0 ]
then
    MY_PS1='\[\033[01;35m\]${REMOTE_PS1}\[\033[01;34m\]\W\[\033[01;31m\]#\[\033[00m\] '
else
    MY_PS1='\[\033[01;35m\]${REMOTE_PS1}\[\033[01;34m\]\W\[\033[01;32m\]\$\[\033[00m\] '
fi

#### Some nice to have variables
export LESS="-XFR"
export MAKEFLAGS="-j $(($(nproc)+1))" # set nproc if it suites you

# Following configurations are modified via script
# Don't modify as it may be modified again
export EDITOR=vi
export VISUAL=gedit

